services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Caju@1234
      MYSQL_DATABASE: caju_dev
      MYSQL_USER: caju
      MYSQL_PASSWORD: caju_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pCaju@1234"]
      timeout: 5s
      retries: 10

  test_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Caju@1234
      MYSQL_DATABASE: caju_test
      MYSQL_USER: caju
      MYSQL_PASSWORD: caju_password
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pCaju@1234"]
      timeout: 5s
      retries: 10

  web:
    build: .
    depends_on:
      - db
      - test_db
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      TEST_DB_HOST: test_db
      MIX_ENV: dev
    volumes:
      - .:/app
    command: mix phx.server

volumes:
  mysql-data: